/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tanks;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author adarb
 */
public class GUI extends javax.swing.JFrame {

    private String name = null;
    private Tank tank; 
    
    /**
     * Creates new form GUI 
     */
    public GUI() {
        initComponents();
        tank = new Tank();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        nameLabel = new javax.swing.JLabel();
        nameJTF = new javax.swing.JTextField();
        tankNumLabel = new javax.swing.JLabel();
        tankNumJTF = new javax.swing.JTextField();
        wellList = new javax.swing.JComboBox<>();
        currLevelLabel = new javax.swing.JLabel();
        feetJTF = new javax.swing.JTextField();
        inchesJTF = new javax.swing.JTextField();
        tankftLabel = new javax.swing.JLabel();
        inchLabel = new javax.swing.JLabel();
        tank1Label = new javax.swing.JLabel();
        tank2Label = new javax.swing.JLabel();
        brineLabel = new javax.swing.JLabel();
        tank1InchLabel = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        tank2feetLabel = new javax.swing.JLabel();
        tank2inJTF = new javax.swing.JTextField();
        tank2ftJTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txJTA = new javax.swing.JTextArea();
        txLabel = new javax.swing.JLabel();
        lastOilLabel = new javax.swing.JLabel();
        lastOilJTF = new javax.swing.JTextField();
        lastFtLabel = new javax.swing.JLabel();
        lastOilInJTF = new javax.swing.JTextField();
        lastOilInLabel = new javax.swing.JLabel();
        selectWellButton = new javax.swing.JButton();
        tankSizeLabel = new javax.swing.JLabel();
        tankSizeJTF = new javax.swing.JTextField();
        actionLabel = new javax.swing.JLabel();
        actionJComboBox = new javax.swing.JComboBox<>();
        brineTankJComboBox = new javax.swing.JComboBox<>();
        dailyProdLabel = new javax.swing.JLabel();
        dailyProdJTF = new javax.swing.JTextField();
        tx = new javax.swing.JButton();
        calledInJCheckBox = new javax.swing.JCheckBox();
        onOffJCheckBox = new javax.swing.JCheckBox();
        insertButton = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameLabel.setText("Name:");

        nameJTF.setText("Well Name");

        tankNumLabel.setText("Tank#");

        tankNumJTF.setText("00000");

        wellList.setMaximumRowCount(40);
        wellList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EAST MARKET", "SAWHILL", "LV_BAPTIST", "SYLVESTER", "DL SMITH", "HALL", "KEPLEY", "DONZELLI", "FLASCK", "WYSS", "GRINDLEY", "RUHL" }));

        currLevelLabel.setText("Current Level:");

        feetJTF.setText("0");

        inchesJTF.setText("0");

        tankftLabel.setText("ft");

        inchLabel.setText("in");

        tank1Label.setText("Tank #1");

        tank2Label.setText(" Tank #2");

        brineLabel.setText("Brine Tank: ");

        tank1InchLabel.setText("in");

        updateButton.setText("Update All");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        tank2feetLabel.setText("ft");

        tank2inJTF.setText("0");

        tank2ftJTF.setText("0");

        txJTA.setColumns(20);
        txJTA.setRows(5);
        txJTA.setText("Treatments");
        jScrollPane1.setViewportView(txJTA);

        txLabel.setText("Treatment:");

        lastOilLabel.setText("Last Oil Level:");

        lastOilJTF.setText("0");

        lastFtLabel.setText("ft");

        lastOilInJTF.setText("0");

        lastOilInLabel.setText("in");

        selectWellButton.setText("Select");
        selectWellButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectButtonClicked(evt);
            }
        });

        tankSizeLabel.setText("Tank Size: ");

        tankSizeJTF.setText("100/140/210");

        actionLabel.setText("Action Needed: ");

        actionJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "DRAIN", "CALL IN WATER", "CALL IN OIL", "SHUT IN", "SHUT OFF", "WAIT ON OIL ", "WAIT ON H20" }));
        actionJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionJComboBoxActionPerformed(evt);
            }
        });

        brineTankJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EMPTY", "1/4 ", "1/2", "3/4", "FULL" }));

        dailyProdLabel.setText("Daily Production:");

        dailyProdJTF.setText("0");

        tx.setText("jButton1");
        tx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txActionPerformed(evt);
            }
        });

        calledInJCheckBox.setText("Oil/Water Called in");

        onOffJCheckBox.setText("On/Off");

        insertButton.setText("Insert New ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(lastOilInJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lastOilInLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(91, 91, 91))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(34, 34, 34)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(onOffJCheckBox)
                                            .addGap(18, 18, 18)
                                            .addComponent(calledInJCheckBox))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(nameLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(nameJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tankNumLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tankNumJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(tankSizeLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tankSizeJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(currLevelLabel)
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(feetJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(tankftLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(inchesJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(tank1InchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(tank1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(24, 24, 24)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tank2Label)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(tank2ftJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(tank2feetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(tank2inJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lastOilLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastOilJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastFtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(139, 139, 139)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(281, 281, 281))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                            .addComponent(insertButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(92, 92, 92)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(wellList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(actionLabel)
                                            .addComponent(dailyProdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(actionJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(selectWellButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dailyProdJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(txLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tx))
                                    .addComponent(inchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(127, 127, 127))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(brineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brineTankJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectWellButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel)
                    .addComponent(nameJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tankNumLabel)
                    .addComponent(tankNumJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wellList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(actionLabel)
                        .addComponent(actionJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(onOffJCheckBox)
                        .addComponent(calledInJCheckBox)
                        .addComponent(insertButton)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dailyProdLabel)
                                    .addComponent(dailyProdJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tank1Label)
                                    .addComponent(tank2Label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inchesJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tank1InchLabel)
                            .addComponent(tank2ftJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tank2feetLabel)
                            .addComponent(tank2inJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tankftLabel)
                            .addComponent(feetJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(currLevelLabel)
                        .addGap(45, 45, 45)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brineLabel)
                    .addComponent(brineTankJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastOilLabel)
                            .addComponent(lastOilJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastFtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastOilInJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastOilInLabel))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tankSizeJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tankSizeLabel))
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tx)
                                .addGap(15, 15, 15)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        nameLabel.getAccessibleContext().setAccessibleName("NameLabel");
        nameJTF.getAccessibleContext().setAccessibleName("nameJTF");
        currLevelLabel.getAccessibleContext().setAccessibleName("currLevelLabel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectButtonClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectButtonClicked
        String well = (String) wellList.getSelectedItem(); // set well equal to select item from well list
       // in jcombo box 
        nameJTF.setText(well);
        // call popGUI
        System.out.println(well);
        tank.popGUI(well,tankSizeJTF, tankNumJTF, onOffJCheckBox, feetJTF, inchesJTF, brineTankJComboBox,
                lastOilJTF, lastOilInJTF, calledInJCheckBox, actionJComboBox, txJTA);
         
    }//GEN-LAST:event_selectButtonClicked

    private void actionJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionJComboBoxActionPerformed
        if (!actionJComboBox.getSelectedItem().equals("None")){
                nameJTF.setBackground(Color.red);
        }
    }//GEN-LAST:event_actionJComboBoxActionPerformed

    private void txActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txActionPerformed
            tank.fillGUI(txJTA);
    }//GEN-LAST:event_txActionPerformed

    //  method will update all fields to match the DB record of the chosen well
    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        String well = (String) wellList.getSelectedItem(); 
        tank.updateDB(well,tankSizeJTF, tankNumJTF, onOffJCheckBox, feetJTF, inchesJTF, brineTankJComboBox,
                lastOilJTF, lastOilInJTF, calledInJCheckBox, actionJComboBox, txJTA);
     
    }//GEN-LAST:event_updateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> actionJComboBox;
    private javax.swing.JLabel actionLabel;
    private javax.swing.JLabel brineLabel;
    public javax.swing.JComboBox<String> brineTankJComboBox;
    public javax.swing.JCheckBox calledInJCheckBox;
    private javax.swing.JLabel currLevelLabel;
    public javax.swing.JTextField dailyProdJTF;
    private javax.swing.JLabel dailyProdLabel;
    public javax.swing.JTextField feetJTF;
    private javax.swing.JLabel inchLabel;
    public javax.swing.JTextField inchesJTF;
    public javax.swing.JButton insertButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastFtLabel;
    private volatile javax.swing.JTextField lastOilInJTF;
    private javax.swing.JLabel lastOilInLabel;
    public javax.swing.JTextField lastOilJTF;
    private javax.swing.JLabel lastOilLabel;
    public javax.swing.JTextField nameJTF;
    private javax.swing.JLabel nameLabel;
    public javax.swing.JCheckBox onOffJCheckBox;
    public javax.swing.JButton selectWellButton;
    private javax.swing.JLabel tank1InchLabel;
    private javax.swing.JLabel tank1Label;
    private javax.swing.JLabel tank2Label;
    public javax.swing.JLabel tank2feetLabel;
    public javax.swing.JTextField tank2ftJTF;
    public javax.swing.JTextField tank2inJTF;
    private javax.swing.JTextField tankNumJTF;
    private javax.swing.JLabel tankNumLabel;
    public javax.swing.JTextField tankSizeJTF;
    private javax.swing.JLabel tankSizeLabel;
    public javax.swing.JLabel tankftLabel;
    public javax.swing.JButton tx;
    public javax.swing.JTextArea txJTA;
    private javax.swing.JLabel txLabel;
    public javax.swing.JButton updateButton;
    private javax.swing.JComboBox<String> wellList;
    // End of variables declaration//GEN-END:variables
}
